# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify
      - name: Go get db
        run: go get ClipsArchiver/internal/db
      - name: Go get clipsarchiver
        run: go get ClipsArchiver/cmd/clipsarchiver
      - name: Go get clipstranscoder
        run: go get ClipsArchiver/cmd/clipstranscoder
        
      - name: Build
        run: go build -v ./...
